import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import './Home.css';

const Home = () => {
  const codeSnippet = `
    function generateCode() {
      console.log('Code is being generated by AI...');
      const data = [];
      for (let i = 0; i < 100; i++) {
        data.push(\`Code line \${i + 1}\`);
      }
      return data.join('\\n');
    }

    const generatedCode = generateCode();
    console.log(generatedCode);
  `;

  const [displayedText, setDisplayedText] = useState('');

  useEffect(() => {
    let i = 0;
    const interval = setInterval(() => {
      const textToShow = codeSnippet.substring(0, i);
      setDisplayedText(textToShow);
      i = (i + 1) % (codeSnippet.length + 1);
    }, 30); // Adjust speed as needed (ms per character)

    return () => clearInterval(interval);
  }, [codeSnippet]);

  return (
    <div className="bg-black text-white min-h-screen">
      <nav>
        <div className="logo-container">
          <span className="zoma-text">Zoma.ai</span>
        </div>
        <div className="nav-links">
          <Link to="/" className="nav-link hover:text-green-300">Home</Link>
          <Link to="/about" className="nav-link hover:text-green-300">About</Link>
          <Link to="/pricing" className="nav-link hover:text-green-300">Pricing</Link>
          <Link to="/api" className="nav-link hover:text-green-300">API</Link>
        </div>
        <div className="logo-container">
          <span className="logo-text">Logo</span> {/* Replace with your logo */}
        </div>
      </nav>
      
      <section className="relative flex flex-col items-center justify-center h-80">
        <div className="absolute inset-0 dots-animation"> ........................</div>
        <div className="relative z-10 text-center">
          <h1 className="text-3xl md:text-4xl font-bold mb-2 md:mb-4 text-animation">AI Enhancement</h1>
          <p className="text-sm md:text-base mb-4 md:mb-8 text-animation">Experience the power of AI with Zoma.ai</p>
          <Link to="/" className="btn-green text-sm md:text-base text-animation">Try Now</Link>
        </div>
      </section>

      {/* Section divider with green line */}
      <hr className="my-8 border-t-2 border-green-600" />

      <section className="bg-black text-green-500 text-center p-4">
        <div className="text-lg mb-2 text-animation">Code is being generated by AI...</div>
        <div className="code-container">
          <div className="code-line typing">{displayedText}</div>
        </div>
      </section>
      
      {/* Add separation gap */}
      <div className="separator"></div>

      <section className="p-8 bg-black text-white text-center">
        <h2 className="text-3xl font-bold mb-4 text-animation">Pricing for GPT-4 Edition</h2>
        <div className="flex flex-wrap justify-center">
          <div className="pricing-card">
            <h3>Standard</h3>
            <p>$19.99/month</p>
            <p>Access to basic AI features.</p>
            <p>Community support.</p>
            <p>Limited API usage.</p>
            <p>Free for first 30 days.</p>
            <button className="btn-green">Choose Standard</button>
          </div>
          <div className="pricing-card">
            <h3>Pro</h3>
            <p>$49.99/month</p>
            <p>Advanced AI capabilities.</p>
            <p>Premium support.</p>
            <p>Extended API usage.</p>
            <p>Free for first 60 days.</p>
            <button className="btn-green">Choose Pro</button>
          </div>
          <div className="pricing-card">
            <h3>Enterprise</h3>
            <p>$99.99/month</p>
            <p>Full suite of AI tools.</p>
            <p>Dedicated support.</p>
            <p>Unlimited API usage.</p>
            <p>Free for first 90 days.</p>
            <button className="btn-green">Choose Enterprise</button>
          </div>
          <div className="pricing-card">
            <h3>Ultimate</h3>
            <p>$199.99/month</p>
            <p>All features unlocked.</p>
            <p>24/7 VIP support.</p>
            <p>Customizable API solutions.</p>
            <p>Free for first 120 days.</p>
            <button className="btn-green">Choose Ultimate</button>
          </div>
        </div>
      </section>
      
      <footer className="footer">
        <div className="space-x-4">
          <Link to="/" className="hover:text-green-300 nav-link">Home</Link>
          <Link to="/" className="hover:text-green-300 nav-link">About</Link>
          <Link to="/" className="hover:text-green-300 nav-link">Pricing</Link>
          <Link to="/" className="hover:text-green-300 nav-link">API</Link>
        </div>
        <div className="mt-4">&copy; 2024 Zoma.ai. All rights reserved.</div>
      </footer>
    </div>
  );
};

export default Home;
